name: ksch_dart_client
description: Abstraction of the API of the K.S.C.H. Workflows backend

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  uuid: ^3.0.4
  http: ^0.13.3

dev_dependencies:
  effective_dart: ^1.3.1
  test: ^1.14.4
